version: "3.7"

services:
  backend:
    image: node:18-alpine
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    environment:
      API_KEY: ${API_KEY}
    command: sh -c "yarn install && yarn dev"
