version: "3.7"

services:
  frontend:
    image: node:18-alpine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    command: sh -c "yarn install && yarn dev"
