services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:3000' # Change the host port to 8080
    environment:
      - NODE_ENV=production
    networks:
      - my_network

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    networks:
      - my_network

networks:
  my_network:
    external: true
